### ISSUE TITLE
proposal: new registry

### ISSUE THREAD

**Issue by axetroy** [zhmushan/deno.sh#1]
I found this to be an interesting domain name

But it does implement the function of deno_registry, which is unavoidable

Can you consider porting https://github.com/axetroy/deno_registry ?

This is my other proposal for the registry

so you can use like this:

```typescript
import { abc } from "https://deno.sh/github.com/zhmushan/abc/mod.ts"
```

Although the import path is longer, the hierarchy is more clear

**Comment by zhmushan** [comment]
This project was used to test my own private code, and it is not so important.
I can transfer this domain name to you for free if you do need it.

**Comment by axetroy** [comment]
@zhmushan 
Thx. 

In fact, I do n’t really need this domain. just a suggestion
